# **NUMPY**

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([0,1,2,3,4])
print(arr)
ls=[0,1,2,3,4]
print(ls)

[0 1 2 3 4]
[0, 1, 2, 3, 4]


In [4]:
ls = [0,1,2,3,4]
arr = np.array(ls)
print(arr)

[0 1 2 3 4]


In [5]:
type(arr)

numpy.ndarray

In [6]:
#array의 크기 확인 
print(arr.shape)
print(arr.dtype) #datatype

(5,)
int32


## **배열의 사칙연산**

In [7]:
print(arr)
print("\narr+2:\n", arr+2)
print("\narr-2:\n", arr-2)
print("\narr*2:\n", arr*2)
print("\narr//2:\n", arr//2)

[0 1 2 3 4]

arr+2:
 [2 3 4 5 6]

arr-2:
 [-2 -1  0  1  2]

arr*2:
 [0 2 4 6 8]

arr//2:
 [0 0 1 1 2]


## **배열의 활용**

In [8]:
arr_small = np.array([1,2,3])
arr_big = np.array([10,20,30])
print(2*arr_small + arr_big)

[12 24 36]


In [9]:
#조건 연산
print(arr_small == 2)
print(arr_big > 10)
print((arr_small==2) | (arr_big>20))

[False  True False]
[False  True  True]
[False  True  True]


In [10]:
ls = [0,1,2,3,4,5,6]
arr = np.array(ls)
arr[arr%2 == 0]

array([0, 2, 4, 6])

In [11]:
arr.shape

(7,)

In [12]:
#2차원 배열 선언
arr_double = np.array([[0,1,2],[3,4,5]])
print(arr_double.shape)
print(arr_double)

(2, 3)
[[0 1 2]
 [3 4 5]]


In [13]:
print(len(arr_double))
print(len(arr_double[0])) # 첫번째 행 길이

2
3


In [14]:
#3차원 배열 선언
arr = [[1,2,3],[4,5,6]],[[10,20,30],[40,50,60]]
arr_triple = np.array(arr)
print(arr_triple.shape)
print(arr_triple)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


## **numpy 함수**
* zeros : 0의 원소를 갖는 배열 생성
* ones : 1의 원소를 갖는 배열 생성
* arange : range와 같이 특정 수열 생성
* T(transpose) : 행렬의 전치 행렬 생성 (행 열 변환)
* reshape : range와 같이 특정 수열 생성

In [19]:
arr_zeros = np.zeros((2,5),dtype='i')
print(arr_zeros)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
arr_ones = np.ones((3,2,5),dtype='i')
print(arr_ones)

[[[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]]]


In [21]:
print(np.arange(10))
print('-------------------')
print(np.arange(1,15,2))

[0 1 2 3 4 5 6 7 8 9]
-------------------
[ 1  3  5  7  9 11 13]


## **transpose**

In [23]:
arr = np.array([[1,2,3],[4,5,6]]) #2*3행렬 생성
print(arr)
print('________')
arr_t = arr.T # 3*2행렬
print(arr_t)

[[1 2 3]
 [4 5 6]]
________
[[1 4]
 [2 5]
 [3 6]]


## **reshape**

In [25]:
arr = np.arange(8)
print(arr)
print("shape:", arr.shape)
print('-----------------')
arr_r = arr.reshape(2,4)
print(arr_r)
print("shape:", arr_r.shape)

[0 1 2 3 4 5 6 7]
shape: (8,)
-----------------
[[0 1 2 3]
 [4 5 6 7]]
shape: (2, 4)


## **numpy연산**
* exp : 지수 함수 적용
* log : 로그 함수 적용
* ** : 벡터의 거듭제곱

In [27]:
arr = np.arange(1,6)
print("기본 배열 :", arr)
print("지수함수 적용 :", np.exp(arr) )
print("로그함수 적용 :", np.log(arr))
print("거듭제곱 적용 :", 10**arr)

기본 배열 : [1 2 3 4 5]
지수함수 적용 : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
로그함수 적용 : [0.         0.69314718 1.09861229 1.38629436 1.60943791]
거듭제곱 적용 : [    10    100   1000  10000 100000]


## **Broad Casting**
* 벡터 연산 시 두 벡터 크기가 같아야함
* 서로 다른 크기의 배열 연산은 **브로드캐스팅**을 통해, 크기가 작은 배열을 반복 확장하여 크기가 큰 배열에 맞춰줌

In [30]:
arr = np.arange(12).reshape(3,4)
arr_sub = np.ones(4, dtype = 'i')
print('arr: \n', arr)
print('\narr_sub: ',arr_sub)
print('---------------')
print(arr+arr_sub)

arr: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

arr_sub:  [1 1 1 1]
---------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## **배열의 기초통계량 (axis = 1: 행 기준, axis = 0 : 열 기준)**
* mean : 배열의 평균
* sum : 배열의 합
* var : 배열의 분산
* std : 배열의 표준편차
* max : 특정 인덱스 항목 삭제
* min : 특정 값 항목 삭제
* median : 라스트 항목 정렬하기

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
print('arr:\n',arr)
print('\n평균:\n',np.mean(arr,axis=1))
print('\n총합:\n',np.sum(arr,axis=0))
print('\n분산:\n',np.var(arr,axis=1))
print('\n편차:\n',np.std(arr,axis=1))
print('\n최대:\n',np.max(arr,axis=0))
print('\n최소:\n',np.min(arr,axis=1))

arr:
 [[1 2 3]
 [4 5 6]]

평균:
 [2. 5.]

총합:
 [5 7 9]

분산:
 [0.66666667 0.66666667]

편차:
 [0.81649658 0.81649658]

최대:
 [4 5 6]

최소:
 [1 4]
